#Creating an empty set
names=set()
names.update(['Omkar','Chaitanya','Nilesh','Tejas','Vinayak'])
print("==============================================")
print('The elements in the set are: ',names)
print("==============================================")
names.remove('Tejas')
names.add("Makarand")
print("After modification :",names)
print("==============================================")
names.discard("Pravin")
names.discard("Tejas")
print("After Deletion : ",names)
print("==============================================")
