print("String functions!!")
s="Hello Here"
s1="Hii123"
print("Strings: \ns=: ",s)
print("s1=: ",s1)
print("=========================================")
print("Function isalnum()")
print("is s alphnumeric? ",s.isalnum())
print("is s1 alphnumeric? ",s1.isalnum())
print("=========================================")
print("Function isalpha()")
print("is s contains all alphabets? ",s.isalpha())
print("is s1 contains all alphabets? ",s.isalpha())
print("=========================================")
digit="1234"
print("String digit:= ",digit)
print("=========================================")
print("Function isdigit()")
print("is s1 contains all digits? ",s1.isdigit())
print("is digit contains all digits? ",digit.isdigit())
print("=========================================")
print("Function join()")
s2 = ' '.join(['We', 'are', 'Coders'])
print(s2)
print("=========================================")
