s="Hello GuYS I am Vinayak"

print("Origibal string: ",s)
print("=========================================")
print("Function capitalize()")
print(s.capitalize())
print("=========================================")
print("Function lower()")
print(s.lower())
print("=========================================")
print("Function upper()")
print(s.upper())
print("=========================================")
print("Function title()")
print(s.title())
print("=========================================")
print("Function swapcase()")
print(s.swapcase())
print("=========================================")
print("Function count()")
print(s.count('a'))
print("=========================================")